In [1]:
import numpy as np
import pandas as pd

                                Shape
Indica la forma del arreglo.

arr = np.random.randint(1,10,(3,2))
arr.shape
---> (3, 2)
arr
---> array([[4, 2],
          [4, 8],
          [4, 3]])

                                Reshape
Transforma el arreglo mientras se mantengan los elementos.

arr.reshape(1,6)
----> array([[4, 2, 4, 8, 4, 3]])
arr.reshape(2,3)
---> array([[4, 2, 4],
          [8, 4, 3]])
np.reshape(arr,(1,6))
---> array([[4, 2, 4, 8, 4, 3]])
Se puede hacer un reshape como lo haría C.

np.reshape(arr,(2,3), 'C')
---> array([[4, 2, 4],
       [8, 4, 3]])

También se puede hacer reshape a como lo haría Fortran.

np.reshape(arr,(2,3), 'F')
---> array([[4, 4, 8],
       [4, 2, 3]])
Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.

np.reshape(arr,(2,3), 'A')
---> array([[4, 2, 4],
       [8, 4, 3]])
No puedes cambiar la "forma" a la "forma" original del array, si tienes un (3,3) no lo puedes pasar a (4,2). 
No respeta los 9 elementos del array original.

In [5]:
arr=np.random.randint(1,10,(3,2))
arr

array([[5, 6],
       [5, 3],
       [2, 8]])

In [7]:
arr.shape

(3, 2)

In [8]:
arr.reshape(1,6)

array([[5, 6, 5, 3, 2, 8]])

In [9]:
arr.reshape(3,2)

array([[5, 6],
       [5, 3],
       [2, 8]])

In [10]:
np.reshape(arr,(1,6))

array([[5, 6, 5, 3, 2, 8]])

In [11]:
#El lenuaje C es la base de Python. 
#C organiza por filas.
np.reshape(arr,(2,3),"C")

array([[5, 6, 5],
       [3, 2, 8]])

In [12]:
#F organiza por columnas.
np.reshape(arr,(2,3),"F")

array([[5, 2, 3],
       [5, 6, 8]])

In [14]:
#A optimaza tiempo.
np.reshape(arr,(2,3),"A")

array([[5, 6, 5],
       [3, 2, 8]])

In [ ]:
#RETO
#Crear un tensor con cualquier dimensionalidad, y aplicar reshape.

In [6]:
arr2=np.random.randint(0,100,(3,2))
arr2

array([[21, 68],
       [70, 80],
       [35, 82]])

In [7]:
arr2.ndim

2

In [9]:
arr2.reshape(2,3,-1)

array([[[21],
        [68],
        [70]],

       [[80],
        [35],
        [82]]])

In [10]:
arr2.ndim

2

In [12]:
arr3=np.random.randint(0,20,(5,4))
arr3

array([[ 6,  0, 11,  7],
       [ 8, 12, 16, 16],
       [14, 10,  4,  7],
       [15,  4,  5, 13],
       [ 0, 11,  5, 15]])

In [13]:
arr3.reshape(2,-1)

array([[ 6,  0, 11,  7,  8, 12, 16, 16, 14, 10],
       [ 4,  7, 15,  4,  5, 13,  0, 11,  5, 15]])

In [15]:
arr3.reshape(4,-1)

array([[ 6,  0, 11,  7,  8],
       [12, 16, 16, 14, 10],
       [ 4,  7, 15,  4,  5],
       [13,  0, 11,  5, 15]])