In [1]:
import numpy as np
import pandas as pd

Vamos a ver cuáles son las funciones que se utilizan normalmente con NumPy cuando analizamos los datos.

arr = np.random.randint(1, 20, 10)
arr
---> array([ 6, 11, 15, 12,  9, 17,  7,  7, 12,  3])

matriz = arr.reshape(2,5)
matriz
---> array([[ 6, 11, 15, 12,  9],
       [17,  7,  7, 12,  3]])
.max Para el máximo

arr.max() ----> 17
matriz.max() ----> 17

Podemos regresar los máximos de cada fila o columna especificando el eje

Recuerda que:

0	Columnas
1	Filas
matriz.max(1) ---> array([15, 17])
matriz.max(0) --->rray([17, 11, 15, 12,  9])

También tenemos .argmax() que nos devuelve la posición del elemento

arr.argmax() ---> 9
En el caso de la matriz nos muestra con un 1 dónde se encuentra el mayor entre las columnas

matriz.argmax(0) ---> array([0, 1, 1, 0, 1])
De forma análoga tenemos .min()

arr.min() ---> 3
arr.argmin() ---> 3
matriz.min(0) ---> array([ 6,  7,  7, 12,  3])
matriz.argmin(1) ---> array([6, 3])
Podemos saber la distancia entre el valor más bajo con el más alto.

arr.ptp() # 17 - 3 ---> 14
matriz.ptp(0)  ---> array([11,  4,  8,  0,  6])

                                Análisis estadístico
Ordenar los elementos:

arr.sort() ---> array([ 3,  6,  7,  7,  9, 11, 12, 12, 15, 17])
Obtener un percentil:

np.percentile(arr, 50) ---> 10.0
Mediana:

np.median(arr) ---> 10.0
Desviación estándar:

np.std(arr) ---> 4.0853396431631
Varianza:

np.var(arr) ---> 16.69
Promedio:

np.mean(arr) ---> 9.9
Lo mismo aplica para las matrices.

np.median(matriz, 1) ---> array([ 7., 12.])

                                Concatenación
Se pueden unir dos arrays

a = np.array([[1,2], [3,4]])
b= np.array([5, 6])
np.concatenate((a,b), axis = 0)

---> ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
El error anterior es debido a que ‘a’ tiene 2 dimensiones, mientras que ‘b’ tiene 1.

a.ndim ---> 2
b.ndim ---> 1
Debemos poner ‘b’ en 2 dimensiones también.

b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)
---> array([[1, 2],
             [3, 4],
             [5, 6]])

De igual manera, podemos agregarlo en el otro eje

np.concatenate((a,b), axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1
    
Como ‘b’ es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.

La transpuesta pone nuestro array en sentido opuesto, si el array original es (1,2), con la transpuesta quedará (2,1)

b.T
---> array([[5],
           [6]])

np.concatenate((a,b.T), axis = 1)
---> array([[1, 2, 5],
               [3, 4, 6]])

                                    Apuntes

El indice 0 con matrices representa a las columnas. 

El indice 1 con matrices representa a las filas. 

argmax retorna el indice del mayor valor. 

ptp() permite ver la distribucion en un arreglo.

Que tanta distancia hay del valor mas bajo, al mas alto. 

La desviacion estandar al cuadrado es igual a la variacion. 

Con .T junto a un arreglo se halla la forma transpuesta.

arr.astype(np.float64) 

arr.astype(np.int8) 

arr.astype(np.bool_) 

arr,astype(np.string_)

En las matrices el eje 1 es para filas y el eje 0 es para columnas 

argmax() muestra el indice del valor máximo.

Muestra la cantidad del número menor al mayor.

Muestra el valor que está en la mitad. 

(El 50%) Organiza de menor a mayor los valores en el arreglo. 

La desviación estandar al cuadrado es igual a la variación.

In [12]:
arr=np.random.randint(1,20,10)
arr

array([12, 18,  9, 18, 13, 10, 15, 11, 16,  5])

In [14]:
matriz=arr.reshape(2,5)
matriz

array([[12, 18,  9, 18, 13],
       [10, 15, 11, 16,  5]])

In [15]:
arr.max()

18

In [16]:
matriz.max()

18

In [17]:
matriz.max(0)

array([12, 18, 11, 18, 13])

In [18]:
matriz.max(1)

array([18, 16])

In [19]:
arr.argmax()

1

In [24]:
matriz

array([[12, 18,  9, 18, 13],
       [10, 15, 11, 16,  5]])

In [22]:
matriz.argmax(0)

array([0, 0, 1, 0, 0], dtype=int64)

In [23]:
matriz.argmax(1)

array([1, 3], dtype=int64)

In [25]:
arr.min()

5

In [26]:
matriz.min()

5

In [27]:
arr.argmin()

9

In [30]:
matriz.argmin()

9

In [31]:
matriz.argmin(0)

array([1, 1, 0, 1, 1], dtype=int64)

In [32]:
matriz.argmin(1)

array([2, 4], dtype=int64)

In [33]:
arr.ptp()

13

In [35]:
matriz.ptp(0)

array([2, 3, 2, 2, 8])

In [36]:
matriz.ptp(1)

array([ 9, 11])

In [39]:
np.percentile(arr,50)

12.5

In [41]:
arr.sort()
arr

array([ 5,  9, 10, 11, 12, 13, 15, 16, 18, 18])

In [42]:
np.median(arr)

12.5

In [43]:
np.median(matriz,0)

array([ 9. , 12. , 13. , 14.5, 15. ])

In [44]:
np.median(matriz,1)

array([10., 16.])

In [45]:
np.std(arr)

3.950949253027682

In [48]:
np.std(arr)**2

15.609999999999998

In [47]:
np.var(arr)

15.61

In [50]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [51]:
a.ndim

2

In [53]:
b=np.array([5,6])
b

array([5, 6])

In [56]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [57]:
b.ndim

1

In [64]:
b=np.expand_dims(b,axis=0)

In [65]:
b.ndim

2

In [66]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [3]:
arr=np.array([1,2,3,4])

In [4]:
arr.dtype

dtype('int32')

In [6]:
arr=np.array([1,2,3,4],dtype="float64")
arr.dtype

dtype('float64')

In [9]:
arr=arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [13]:
arr=np.array([0,1,2,3,4])
arr=arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [15]:
arr=np.array([0,1,2,3,4])
arr=arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

                                Temas de platzi

In [17]:
arr=np.array(["0","1","2","3","4"])
arr=arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [4]:
arr=np.random.randint(1,20,10)
arr

array([ 5, 12,  3,  9,  6,  3, 15, 19, 16, 18])

In [5]:
arr.shape

(10,)

In [7]:
matriz=arr.reshape(2,5)
matriz

array([[ 5, 12,  3,  9,  6],
       [ 3, 15, 19, 16, 18]])

In [8]:
arr.max()

19

In [9]:
matriz.max()

19

In [10]:
matriz.max(1)

array([12, 19])

In [11]:
matriz.max(0)

array([ 5, 15, 19, 16, 18])

In [12]:
matriz.argmax()

7

In [16]:
print(matriz)

[[ 5 12  3  9  6]
 [ 3 15 19 16 18]]


In [15]:
matriz.argmax(0)

array([0, 1, 1, 1, 1], dtype=int64)

In [17]:
matriz.argmax(1)

array([1, 2], dtype=int64)

In [18]:
arr.min()

3

In [19]:
arr

array([ 5, 12,  3,  9,  6,  3, 15, 19, 16, 18])

In [26]:
arr.argmin()

2

In [27]:
arr.ptp()

16

In [28]:
matriz.ptp()

16

In [29]:
np.percentile(arr,50)

10.5

In [30]:
np.percentile(arr,100)

19.0

In [31]:
arr.sort()
arr

array([ 3,  3,  5,  6,  9, 12, 15, 16, 18, 19])

In [32]:
np.median(arr)

10.5

In [34]:
matriz

array([[ 3,  3,  5,  6,  9],
       [12, 15, 16, 18, 19]])

In [33]:
np.median(matriz,0)

array([ 7.5,  9. , 10.5, 12. , 14. ])

In [36]:
np.median(matriz,1)

array([ 5., 16.])

In [38]:
np.std(arr)

5.885575587824865

In [39]:
np.std(matriz,0)

array([4.5, 6. , 5.5, 6. , 5. ])

In [40]:
np.std(matriz,1)

array([2.22710575, 2.44948974])

In [41]:
np.std(matriz)

5.885575587824865

In [42]:
np.std(arr)**2

34.64

In [43]:
np.var(arr)

34.64

In [44]:
np.mean(arr)

10.6

In [102]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])

In [103]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [93]:
b=np.squeeze(b)
b

array([7, 8, 9])

In [105]:
b=np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [109]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
a

array([[1, 2],
       [3, 4]])

In [106]:
b

array([[5, 6]])

In [108]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])