In [1]:
import numpy as np
import pandas as pd

                                Apuntes

Se mete la condición entre corchetes al objeto de tipo array de numpy.
Hacer un nuevo array con con condiciones.

Las condiciones nos permiten hacer consultas más específicas.

arr = np.linspace(1,10,10, dtype = 'int8')
arr 
---> array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Regresa un array de booleanos dónde la condición se cumple.

indices_cond = arr > 5
indices_cond
---> array([False, False, False, False, False,  True,  True,  True,  True, True])

Regresa los valores para dónde la condiciones True.

arr[indices_cond] 
---> array([ 6,  7,  8,  9, 10], dtype=int8)

Múltiples condiciones.

arr[(arr > 5) & (arr < 9)] 
---> array([6, 7, 8], dtype=int8)

Modificar los valores que cumplan la condición.

arr[arr > 5] = 99
arr
---> array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [3]:
arr=np.linspace(1,20,10, dtype="int8")
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20], dtype=int8)

In [4]:
indices_cond=arr>5
indices_cond

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [5]:
arr[indices_cond]

array([ 7,  9, 11, 13, 15, 17, 20], dtype=int8)

In [6]:
arr[(arr>5)&(arr<9)]

array([7], dtype=int8)

In [8]:
arr[arr>5]=99
arr

array([ 1,  3,  5, 99, 99, 99, 99, 99, 99, 99], dtype=int8)

In [10]:
arr[arr==99]

array([99, 99, 99, 99, 99, 99, 99], dtype=int8)