In [1]:
import numpy as np
import pandas as pd

In [4]:
arr=np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
indices_cond=arr>5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
arr[(arr>5)&(arr<9)]

array([6, 7, 8], dtype=int8)

In [12]:
arr[arr>5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [13]:
arr2=np.linspace(2,60,40, dtype="int8")
arr2

array([ 2,  3,  4,  6,  7,  9, 10, 12, 13, 15, 16, 18, 19, 21, 22, 24, 25,
       27, 28, 30, 31, 33, 34, 36, 37, 39, 40, 42, 43, 45, 46, 48, 49, 51,
       52, 54, 55, 57, 58, 60], dtype=int8)

In [14]:
arr2_copy=arr2.copy()
arr2_copy

array([ 2,  3,  4,  6,  7,  9, 10, 12, 13, 15, 16, 18, 19, 21, 22, 24, 25,
       27, 28, 30, 31, 33, 34, 36, 37, 39, 40, 42, 43, 45, 46, 48, 49, 51,
       52, 54, 55, 57, 58, 60], dtype=int8)

In [15]:
arr2_copy[(arr2_copy>50)&(arr2_copy<60)]

array([51, 52, 54, 55, 57, 58], dtype=int8)

In [17]:
arr2_copy[(arr2_copy>30)&(arr2_copy<40)]=20

In [18]:
arr2_copy[arr2_copy==20]

array([20, 20, 20, 20, 20, 20], dtype=int8)

In [19]:
arr2_copy

array([ 2,  3,  4,  6,  7,  9, 10, 12, 13, 15, 16, 18, 19, 21, 22, 24, 25,
       27, 28, 30, 20, 20, 20, 20, 20, 20, 40, 42, 43, 45, 46, 48, 49, 51,
       52, 54, 55, 57, 58, 60], dtype=int8)

In [20]:
arr2

array([ 2,  3,  4,  6,  7,  9, 10, 12, 13, 15, 16, 18, 19, 21, 22, 24, 25,
       27, 28, 30, 31, 33, 34, 36, 37, 39, 40, 42, 43, 45, 46, 48, 49, 51,
       52, 54, 55, 57, 58, 60], dtype=int8)